export function getInitialAppState() {
  return {
    settings: {
      commission: 12.5,
      cancellationFee: 15,
      otpWindowMinutes: 15,
    },
    users: [
      { id: 'driver-1', name: 'דני לוי', email: 'driver@sharecharge.app', role: 'driver', verified: true, blocked: false, spend: 286 },
      { id: 'driver-2', name: 'נועה כהן', email: 'noa@sharecharge.app', role: 'driver', verified: true, blocked: false, spend: 154 },
      { id: 'host-1', name: 'מיכל רוזן', email: 'host@sharecharge.app', role: 'host', verified: true, blocked: false, revenue: 1840 },
      { id: 'host-2', name: 'אורי שגב', email: 'host2@sharecharge.app', role: 'host', verified: false, blocked: false, revenue: 620 },
    ],
    stations: [
      {
        id: 'station-1',
        hostId: 'host-1',
        name: 'עמדת וילה ירוקה',
        address: 'הפרדס 18, רמת השרון',
        lat: 32.1378,
        lng: 34.8403,
        distance: 0.7,
        power: 22,
        plug: 'Type 2',
        pricePerKwh: 1.35,
        available: true,
        rating: 4.9,
        photos: 6,
        termsText: 'גישה לעמדה מהחניה · נא לתאם זמן הגעה',
      },
      {
        id: 'station-2',
        hostId: 'host-1',
        name: 'חניה פרטית שקטה',
        address: 'קהילת ונציה 4, תל אביב',
        lat: 32.0853,
        lng: 34.7818,
        distance: 1.4,
        power: 11,
        plug: 'Type 2',
        pricePerKwh: 1.18,
        available: true,
        rating: 4.8,
        photos: 4,
        termsText: 'חניה צרה — נא להקפיד על פתיחת מראות',
      },
      {
        id: 'station-3',
        hostId: 'host-2',
        name: 'מטען מהיר בחצר',
        address: 'הגליל 9, הרצליה',
        lat: 32.1624,
        lng: 34.8447,
        distance: 2.1,
        power: 50,
        plug: 'CCS',
        pricePerKwh: 1.55,
        available: true,
        rating: 4.7,
        photos: 3,
        termsText: 'CCS בלבד · שעות שקט 22:00–07:00',
      },
    ],
    bookings: [],
    transactions: [],
    disputes: [],
    events: [
      { id: 'event-1', text: 'מערכת הדמו הופעלה ומוכנה להזמנות', type: 'system', time: Date.now() - 1000 * 60 * 12 },
    ],
  };
}
