export function getInitialAppState() {
  return {
    settings: {
      commission: 12.5,
      cancellationFee: 15,
      otpWindowMinutes: 15,
    },
    users: [
      { id: 'driver-1', name: 'דני לוי', email: 'driver@sharecharge.app', role: 'driver', verified: true, blocked: false, spend: 286 },
      { id: 'driver-2', name: 'נועה כהן', email: 'noa@sharecharge.app', role: 'driver', verified: true, blocked: false, spend: 154 },
      { id: 'host-1', name: 'מיכל רוזן', email: 'host@sharecharge.app', role: 'host', verified: true, blocked: false, revenue: 1840 },
      { id: 'host-2', name: 'אורי שגב', email: 'host2@sharecharge.app', role: 'host', verified: false, blocked: false, revenue: 620 },
    ],
    stations: [
      {
        id: 'station-1',
        hostId: 'host-1',
        name: 'עמדת וילה ירוקה',
        address: 'הפרדס 18, רמת השרון',
        lat: 32.1378,
        lng: 34.8403,
        distance: 0.7,
        power: 22,
        plug: 'Type 2',
        pricePerKwh: 1.35,
        serviceCategory: 'charging',
        available: true,
        rating: 4.9,
        photos: 6,
        termsText: 'גישה לעמדה מהחניה · נא לתאם זמן הגעה',
      },
      {
        id: 'station-2',
        hostId: 'host-1',
        name: 'חניה פרטית שקטה',
        address: 'קהילת ונציה 4, תל אביב',
        lat: 32.0853,
        lng: 34.7818,
        distance: 1.4,
        power: 11,
        plug: 'Type 2',
        pricePerKwh: 1.18,
        serviceCategory: 'charging',
        available: true,
        rating: 4.8,
        photos: 4,
        termsText: 'חניה צרה — נא להקפיד על פתיחת מראות',
      },
      {
        id: 'station-3',
        hostId: 'host-2',
        name: 'מטען מהיר בחצר',
        address: 'הגליל 9, הרצליה',
        lat: 32.1624,
        lng: 34.8447,
        distance: 2.1,
        power: 50,
        plug: 'CCS',
        pricePerKwh: 1.55,
        serviceCategory: 'charging',
        available: true,
        rating: 4.7,
        photos: 3,
        termsText: 'CCS בלבד · שעות שקט 22:00–07:00',
      },
      {
        id: 'bakery-1', hostId: 'host-1', serviceCategory: 'bakery', name: 'פנזריה רוזן',
        address: 'אחוזה 12, רמת השרון', lat: 32.1395, lng: 34.8395, distance: 0.9, power: 0, plug: 'מגשים',
        pricePerKwh: 45, available: true, rating: 4.8, photos: 5, termsText: 'הזמנה מראש · איסוף בחנות',
      },
      {
        id: 'tow-1', hostId: 'host-2', serviceCategory: 'tow', name: 'גרר מהיר 24/7',
        address: 'המסגר 5, הרצליה', lat: 32.164, lng: 34.846, distance: 2.3, power: 0, plug: 'גרירה',
        pricePerKwh: 180, available: true, rating: 4.9, photos: 3, termsText: 'הגעה עד 40 דק׳',
      },
      {
        id: 'garage-1', hostId: 'host-1', serviceCategory: 'garage', name: 'מוסך אלון',
        address: 'החרושת 3, רמת השרון', lat: 32.1365, lng: 34.8425, distance: 1.1, power: 0, plug: 'תיקון',
        pricePerKwh: 95, available: true, rating: 4.7, photos: 4, termsText: 'אבחון + תיקון',
      },
      {
        id: 'charge-jlm-1', hostId: 'host-1', serviceCategory: 'charging', name: 'עמדת בלוי',
        address: 'הרב בלוי 8, ירושלים', lat: 31.7946, lng: 35.2137, distance: 0.5, power: 22, plug: 'Type 2',
        pricePerKwh: 1.35, available: true, rating: 4.9, photos: 4, termsText: 'חניה פרטית · תיאום מראש',
      },
      {
        id: 'fuel-jlm-1', hostId: 'host-2', serviceCategory: 'fuel', name: 'דלק חירום ירושלים',
        address: 'רחוב בית הדפוס, ירושלים', lat: 31.7515, lng: 35.2182, distance: 0.3, power: 0, plug: 'דלק',
        pricePerKwh: 35, available: true, rating: 4.8, photos: 2, termsText: 'הגעה עם דלק · תשלום לפי ליטר',
      },
      {
        id: 'puncture-jlm-1', hostId: 'host-1', serviceCategory: 'puncture', name: "פנצ'ריה מהירה ירושלים",
        address: 'יפו 120, ירושלים', lat: 31.7855, lng: 35.2055, distance: 0.8, power: 0, plug: "פנצ'",
        pricePerKwh: 55, available: true, rating: 4.9, photos: 3, termsText: 'תיקון בשטח · עד 30 דק׳',
      },
      {
        id: 'tow-jlm-1', hostId: 'host-2', serviceCategory: 'tow', name: 'גרר ירושלים 24/7',
        address: 'שדרות בegin 50, ירושלים', lat: 31.792, lng: 35.195, distance: 1.2, power: 0, plug: 'גרירה',
        pricePerKwh: 190, available: true, rating: 4.8, photos: 2, termsText: 'גרירה עירונית ובין-עירונית',
      },
      {
        id: 'garage-jlm-1', hostId: 'host-1', serviceCategory: 'garage', name: 'מוסך + מצבר ירושלים',
        address: 'הארז 5, ירושלים', lat: 31.788, lng: 35.21, distance: 0.9, power: 0, plug: 'מצבר',
        pricePerKwh: 100, available: true, rating: 4.7, photos: 3, termsText: 'התנעה · החלפת מצבר · תיקונים',
      },
    ],
    bookings: [],
    transactions: [],
    disputes: [],
    serviceRequests: [],
    serviceBids: [],
    payments: [],
    paymentMethods: [],
    events: [
      { id: 'event-1', text: 'המערכת מוכנה לקבלת הזמנות', type: 'system', time: Date.now() - 1000 * 60 * 12 },
    ],
  };
}
